/**
 * @fileoverview Controller for AEO Linter Chrome DevTools Panel.
 * Supports:
 * 1. Importing previously saved AEO JSON audit reports (file picker & drag-and-drop).
 * 2. Auditing active tab directly within DevTools using the full in-browser engine.
 * 3. Exporting audit reports.
 * 4. Rendering interactive Lighthouse-style score gauges and structured tables.
 */

import { BrowserAeoEngine } from './engine.js';

// State
let currentReport = null;

// DOM Elements
const importFileInput = document.getElementById('import-file-input');
const btnImport = document.getElementById('btn-import');
const btnDropzoneImport = document.getElementById('btn-dropzone-import');
const btnAuditPage = document.getElementById('btn-audit-page');
const btnExportJson = document.getElementById('btn-export-json');
const dropzone = document.getElementById('dropzone');
const reportContent = document.getElementById('report-content');

// --- 1. Import Handlers ---

btnImport?.addEventListener('click', () => importFileInput?.click());
btnDropzoneImport?.addEventListener('click', () => importFileInput?.click());

importFileInput?.addEventListener('change', (e) => {
  const file = e.target.files?.[0];
  if (file) {
    readAndLoadJsonFile(file);
  }
  importFileInput.value = '';
});

// Drag and drop handlers
['dragenter', 'dragover'].forEach((eventName) => {
  window.addEventListener(eventName, (e) => {
    e.preventDefault();
    dropzone?.classList.add('drag-over');
  });
});

['dragleave', 'drop'].forEach((eventName) => {
  window.addEventListener(eventName, (e) => {
    e.preventDefault();
    dropzone?.classList.remove('drag-over');
  });
});

window.addEventListener('drop', (e) => {
  e.preventDefault();
  const file = e.dataTransfer?.files?.[0];
  if (file && file.name.endsWith('.json')) {
    readAndLoadJsonFile(file);
  } else if (file) {
    alert('Please upload a valid .json file generated by AEO Linter.');
  }
});

function readAndLoadJsonFile(file) {
  const reader = new FileReader();
  reader.onload = (event) => {
    try {
      const data = JSON.parse(event.target.result);
      if (!validateAeoReport(data)) {
        alert('Invalid AEO Report format. Missing categories or overall score.');
        return;
      }
      currentReport = data;
      renderReport(currentReport);
    } catch (err) {
      alert(`Error reading JSON file: ${err.message}`);
    }
  };
  reader.readAsText(file);
}

function validateAeoReport(data) {
  return data && typeof data === 'object' && ('overallScore' in data || 'categories' in data);
}

// --- 2. Export Handler ---

btnExportJson?.addEventListener('click', () => {
  if (!currentReport) return;
  const jsonStr = JSON.stringify(currentReport, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const host = currentReport.url ? new URL(currentReport.url).hostname.replace(/[^a-z0-9]/gi, '_') : 'aeo-report';
  a.href = url;
  a.download = `aeo-report-${host}-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
});

// --- 3. Audit Active Page Handler (Using BrowserAeoEngine) ---

btnAuditPage?.addEventListener('click', () => {
  if (typeof chrome === 'undefined' || !chrome.devtools || !chrome.devtools.inspectedWindow) {
    alert('Live page auditing is active inside Chrome DevTools. To inspect external reports, use "Import JSON".');
    return;
  }

  btnAuditPage.disabled = true;
  btnAuditPage.textContent = '⚡ Auditing...';

  chrome.devtools.inspectedWindow.eval(
    `(() => {
      return {
        url: window.location.href,
        html: document.documentElement.outerHTML
      };
    })()`,
    async (pageData, isException) => {
      btnAuditPage.disabled = false;
      btnAuditPage.textContent = '⚡ Audit Page';

      if (isException || !pageData) {
        alert('Error inspecting active tab.');
        return;
      }

      try {
        const report = await BrowserAeoEngine.runAudit(pageData.url, pageData.html);
        currentReport = report;
        renderReport(currentReport);
      } catch (err) {
        alert(`Audit failed: ${err.message}`);
      }
    }
  );
});

// --- 4. Render Report Function ---

function renderReport(report) {
  dropzone.style.display = 'none';
  reportContent.style.display = 'block';
  btnExportJson.style.display = 'inline-flex';

  const formatScore = (score) => {
    if (score === null || score === undefined) return 'N/A';
    return score <= 1 ? Math.round(score * 100) : Math.round(score);
  };

  const getScoreColor = (score) => {
    if (score === null || score === undefined) return '#8b949e';
    const s = score <= 1 ? score * 100 : score;
    if (s >= 90) return '#0cce6b';
    if (s >= 50) return '#ffa400';
    return '#ff4e42';
  };

  const getScoreBadgeClass = (score) => {
    if (score === null || score === undefined) return 'score-na';
    const s = score <= 1 ? score * 100 : score;
    if (s >= 90) return 'score-pass';
    if (s >= 50) return 'score-average';
    return 'score-fail';
  };

  const renderGauge = (score, title) => {
    const s = formatScore(score);
    const color = getScoreColor(score);
    const numScore = typeof s === 'number' ? s : 0;
    const strokeDashoffset = 283 - (283 * numScore) / 100;

    return `
      <div class="gauge-card">
        <svg class="gauge-svg" viewBox="0 0 100 100">
          <circle class="gauge-bg" cx="50" cy="50" r="45" />
          <circle class="gauge-fill" cx="50" cy="50" r="45"
            style="stroke: ${color}; stroke-dasharray: 283; stroke-dashoffset: ${strokeDashoffset};" />
        </svg>
        <div class="gauge-score" style="color: ${color};">${s}</div>
        <div class="gauge-label">${title}</div>
      </div>
    `;
  };

  const renderAuditCard = (audit) => {
    const scoreVal = formatScore(audit.score);
    const badgeClass = getScoreBadgeClass(audit.score);

    return `
      <details class="audit-card">
        <summary class="audit-summary">
          <span class="status-dot ${badgeClass}"></span>
          <span class="audit-name">${audit.title}</span>
          ${audit.displayValue ? `<span class="audit-display-val">${audit.displayValue}</span>` : ''}
          <span class="audit-score-pill ${badgeClass}">${scoreVal}</span>
        </summary>
        <div class="audit-body">
          <p class="audit-desc">${audit.description || ''}</p>
          ${audit.explanation ? `<p class="audit-explanation"><strong>Diagnostic:</strong> ${audit.explanation}</p>` : ''}
        </div>
      </details>
    `;
  };

  const renderCategory = (cat) => {
    const catScore = formatScore(cat.score);
    const badgeClass = getScoreBadgeClass(cat.score);

    return `
      <section class="category-section">
        <div class="cat-head">
          <div>
            <h2 class="cat-title">${cat.title}</h2>
            <p class="cat-desc">${cat.description || ''}</p>
          </div>
          <div class="cat-score-pill ${badgeClass}">
            ${catScore} / 100
          </div>
        </div>
        <div class="audits-list">
          ${(cat.auditRefs || []).map((ref) => renderAuditCard(ref.result || ref)).join('')}
        </div>
      </section>
    `;
  };

  const categories = report.categories || {};
  const dateStr = report.fetchTime ? new Date(report.fetchTime).toLocaleString('en-US') : 'N/A';

  reportContent.innerHTML = `
    <div class="report-header">
      <div>
        <h1 class="report-url">${report.url || 'Audit Report'}</h1>
        <div class="report-meta">Audited on ${dateStr} &bull; Engine v${report.aeoVersion || '0.1.3'}</div>
      </div>
    </div>

    <div class="gauges-grid">
      ${renderGauge(report.overallScore, 'Overall AEO')}
      ${Object.values(categories)
        .map((cat) => renderGauge(cat.score, cat.title))
        .join('')}
    </div>

    ${Object.values(categories)
      .map((cat) => renderCategory(cat))
      .join('')}
  `;
}
